// Generated by Wrangler on Sun Mar 31 2024 01:04:03 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	ASTRO_STUDIO_APP_TOKEN: string;
	ASTRO_STUDIO_REMOTE_DB_URL: string;
	OPENAI_API_KEY: string;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}