// Generated by Wrangler on Thu Mar 28 2024 20:30:12 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	ASTRO_STUDIO_APP_TOKEN: string;
	ASTRO_STUDIO_REMOTE_DB_URL: string;
	OPENAI_API_KEY: string;
}
